mod accel;
mod app;
mod bridge;
mod columns;
mod detail;
mod error;
mod format;
mod panic_hook;
mod poll;
mod sidebar;
mod speed;
mod sidebar_view;
mod skin;
mod skin_tokens;

// Generated by slint_build::compile in build.rs
slint::include_modules!();

use std::sync::Arc;

use parking_lot::Mutex;
use slint::Model as _;

/// Wire a Tweaks-overlay axis callback that follows the
/// "parse string → mutate field → apply tokens → update Slint
/// property" template (M172b skin/theme/density/radius axes).
///
/// Usage:
/// ```ignore
/// wire_skin_axis!(main_window, state, on_tweaks_skin_changed,
///                 skin, skin::Skin, set_current_skin);
/// ```
///
/// For axes that don't fit this template — Layout (label↔token mapping)
/// and the toggles (no string to parse) — use a hand-written block.
macro_rules! wire_skin_axis {
    ($window:ident, $state:ident, $callback:ident, $field:ident, $enum_ty:ty, $setter:ident) => {{
        use std::str::FromStr as _;
        let weak = $window.as_weak();
        let cb_state = $state.clone();
        $window.$callback(move |s| {
            if let Ok(new_value) = <$enum_ty>::from_str(s.as_str()) {
                let skin_settings = {
                    let mut st = cb_state.lock();
                    st.skin.$field = new_value;
                    st.skin_dirty = true;
                    st.skin
                };
                skin_settings.apply(&weak);
                if let Some(win) = weak.upgrade() {
                    win.$setter(s.clone());
                }
            }
        });
    }};
}

fn main() -> Result<(), error::GuiError> {
    // 1. Install panic hook.
    panic_hook::install();

    // 2. Init tracing.
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env().unwrap_or_else(|_| "info".into()),
        )
        .with_target(false)
        .init();

    // 3. Load settings + column config.
    let config = irontide_config::load(None, &irontide_config::ConfigFile::default())
        .map_err(|e| error::GuiError::Config(e.to_string()))?;
    let gui_config = {
        let path = irontide_config::resolve_config_path(None);
        if path.exists() {
            let text = std::fs::read_to_string(&path).unwrap_or_default();
            let cf: irontide_config::ConfigFile = toml::from_str(&text).unwrap_or_default();
            cf.gui
        } else {
            irontide_config::GuiConfig::default()
        }
    };
    let col_config = columns::ColumnConfig::from_gui_config(&gui_config);
    let skin_settings = skin::SkinSettings::from_gui_config(&gui_config);
    let settings = config;

    // 4. Create shutdown channel + app state.
    let (shutdown_tx, shutdown_rx) = tokio::sync::oneshot::channel();
    let mut initial_state = app::AppState::new(shutdown_tx, col_config, skin_settings);
    // M173 Lane A task A9: hydrate persisted sidebar state. Absent
    // [gui.sidebar] table → all defaults; corrupt token → silent
    // fallback to Library::All.
    if let Some(sb) = gui_config.sidebar.as_ref() {
        initial_state.load_sidebar_config(sb);
    }
    let state = Arc::new(Mutex::new(initial_state));

    // 5. Create main window + push initial skin into Tokens global.
    let main_window = MainWindow::new()?;
    {
        let weak = main_window.as_weak();
        let st = state.lock();
        st.skin.apply(&weak);
        // Seed the Tweaks overlay's current-* pill state so the UI
        // reflects the persisted config on first paint.
        main_window.set_current_skin(st.skin.skin.to_string().into());
        main_window.set_current_theme(st.skin.theme.to_string().into());
        main_window.set_current_density(st.skin.density.to_string().into());
        main_window.set_current_radius(st.skin.radius.to_string().into());
        // M176: layout / L3 sidebar mode / inspector visibility.
        main_window.set_current_layout_label(st.skin.layout.label().into());
        main_window.set_current_l3_sidebar_mode(st.skin.l3_sidebar_mode.to_string().into());
        let effective_inspector = st
            .skin
            .inspector_shown
            .unwrap_or_else(|| skin::default_inspector_shown(st.skin.layout));
        main_window.set_inspector_shown(effective_inspector);
        // M173 Lane A task A9: seed sidebar collapsed flags from
        // persisted state so the first-paint sidebar matches the
        // user's last session.
        main_window.set_sidebar_library_collapsed(st.sidebar_library_collapsed);
        main_window.set_sidebar_category_collapsed(st.sidebar_category_collapsed);
        main_window.set_sidebar_tag_collapsed(st.sidebar_tag_collapsed);
        main_window.set_sidebar_tracker_collapsed(st.sidebar_tracker_collapsed);
    }

    // 6. Wire menu callbacks.
    let weak = main_window.as_weak();
    let cb_state = state.clone();
    main_window.on_menu_file_action(move |index| {
        if let Some(action) = app::MenuAction::from_index(index) {
            bridge::handle_menu_action(action, &weak, &cb_state);
        }
    });

    // 6b. Wire sort callback.
    {
        let cb_state = state.clone();
        main_window.on_sort_requested(move |col_index| {
            let Some(col) = columns::ColumnId::from_index(col_index) else {
                return;
            };
            let mut st = cb_state.lock();
            if st.sort.column == col {
                st.sort.ascending = !st.sort.ascending;
            } else {
                st.sort.column = col;
                st.sort.ascending = true;
            }
        });
    }

    // 6c. Wire row-click callback.
    {
        let cb_state = state.clone();
        main_window.on_row_clicked(move |info_hash, shift, ctrl| {
            let hash = info_hash.as_str();
            let (selected, primary) = {
                let mut st = cb_state.lock();
                if ctrl {
                    st.selection_ctrl_click(hash);
                } else if shift {
                    st.selection_shift_click(hash);
                } else {
                    st.selection_click(hash);
                }
                (st.selected.clone(), st.primary_selected().map(str::to_owned))
            };
            crate::poll::update_selection(&selected);
            crate::poll::update_primary_selection(primary.as_deref());
        });
    }

    // 6d. Wire add-magnet dialog callbacks.
    {
        let cb_state = state.clone();
        main_window.on_add_magnet_confirmed(move |uri, dir| {
            let cmd_tx = {
                let st = cb_state.lock();
                st.cmd_tx.clone()
            };
            if let Some(tx) = cmd_tx {
                let download_dir = if dir.is_empty() {
                    None
                } else {
                    Some(dir.to_string())
                };
                let _ = tx.send(app::GuiCommand::AddMagnet {
                    uri: uri.to_string(),
                    download_dir,
                });
            }
        });
    }

    {
        let weak = main_window.as_weak();
        let cb_state = state.clone();
        main_window.on_browse_magnet_download_dir(move || {
            bridge::handle_browse_download_dir(&weak, &cb_state);
        });
    }

    // 6e. Wire add-torrent dialog callbacks.
    {
        let cb_state = state.clone();
        main_window.on_add_torrent_confirmed(move |path, dir| {
            let cmd_tx = {
                let st = cb_state.lock();
                st.cmd_tx.clone()
            };
            if let Some(tx) = cmd_tx {
                let download_dir = if dir.is_empty() {
                    None
                } else {
                    Some(dir.to_string())
                };
                let _ = tx.send(app::GuiCommand::AddTorrentFile {
                    path: path.to_string(),
                    download_dir,
                });
            }
        });
    }

    {
        let weak = main_window.as_weak();
        main_window.on_browse_torrent_file(move || {
            bridge::handle_browse_torrent_file(&weak);
        });
    }

    {
        let weak = main_window.as_weak();
        let cb_state = state.clone();
        main_window.on_browse_torrent_download_dir(move || {
            bridge::handle_browse_download_dir(&weak, &cb_state);
        });
    }

    // 6f. Wire right-click context menu.
    {
        let cb_state = state.clone();
        let weak = main_window.as_weak();
        main_window.on_row_right_clicked(move |info_hash, x, y| {
            let hash = info_hash.to_string();
            // If right-clicked row is not selected, select it first.
            let (selected, primary) = {
                let mut st = cb_state.lock();
                if !st.selected.contains(&hash) {
                    st.selection_click(&hash);
                }
                (st.selected.clone(), st.primary_selected().map(str::to_owned))
            };
            // Immediately update selection in model.
            crate::poll::update_selection(&selected);
            crate::poll::update_primary_selection(primary.as_deref());

            // Show context menu at cursor position.
            let _ = weak.upgrade_in_event_loop(move |win| {
                // Compute smart enable/disable state from the torrent model.
                let model = win.get_torrent_model();
                let mut state_strings: Vec<String> = Vec::new();

                for i in 0..model.row_count() {
                    if let Some(row) = model.row_data(i)
                        && selected.contains(row.info_hash.as_str())
                    {
                        state_strings.push(row.state.to_string());
                    }
                }

                let state_refs: Vec<&str> = state_strings.iter().map(String::as_str).collect();
                let ctx = app::ContextMenuState::compute(&state_refs);

                win.set_ctx_can_pause(ctx.can_pause);
                win.set_ctx_can_resume(ctx.can_resume);
                win.set_ctx_can_seed_only(ctx.can_seed_only);
                win.set_ctx_can_resume_download(ctx.can_resume_download);
                win.set_ctx_can_recheck(ctx.can_recheck);

                win.set_context_menu_x(x);
                win.set_context_menu_y(y);
                win.set_show_context_menu(true);
            });
        });
    }

    // 6g. Wire context menu action dispatch.
    {
        let cb_state = state.clone();
        let weak = main_window.as_weak();
        main_window.on_context_action(move |action_index| {
            use app::ContextAction;

            let Some(action) = ContextAction::from_index(action_index) else {
                return;
            };
            let hashes: Vec<String> = {
                let st = cb_state.lock();
                st.selected.iter().cloned().collect()
            };

            // Remove/RemoveAndDelete: show confirmation dialog instead of immediate action.
            if matches!(
                action,
                ContextAction::Remove | ContextAction::RemoveAndDelete
            ) {
                let delete_files = matches!(action, ContextAction::RemoveAndDelete);
                let count = i32::try_from(hashes.len()).unwrap_or(i32::MAX);
                let _ = weak.upgrade_in_event_loop(move |win| {
                    win.set_delete_dialog_count(count);
                    win.set_delete_dialog_delete_files(delete_files);
                    win.set_show_delete_dialog(true);
                });
                return;
            }

            let cmd_tx = {
                let st = cb_state.lock();
                st.cmd_tx.clone()
            };
            let Some(tx) = cmd_tx else { return };

            let cmd = match action {
                ContextAction::Pause => app::GuiCommand::PauseTorrents { hashes },
                ContextAction::Resume => app::GuiCommand::ResumeTorrents { hashes },
                ContextAction::SeedOnly => app::GuiCommand::SetSeedMode {
                    hashes,
                    enabled: true,
                },
                ContextAction::ResumeDownload => app::GuiCommand::SetSeedMode {
                    hashes,
                    enabled: false,
                },
                ContextAction::Recheck => app::GuiCommand::ForceRecheck { hashes },
                ContextAction::ForceReannounce => app::GuiCommand::ForceReannounce { hashes },
                // Handled by the confirmation dialog above; unreachable here.
                ContextAction::Remove | ContextAction::RemoveAndDelete => return,
            };
            let _ = tx.send(cmd);
        });
    }

    // 6h. Wire delete confirmation callback.
    {
        let cb_state = state.clone();
        main_window.on_delete_confirmed(move |delete_files| {
            let (hashes, cmd_tx) = {
                let mut st = cb_state.lock();
                let hashes: Vec<String> = st.selected.iter().cloned().collect();
                // ── M177 D-eng-4 (Iron Rule): prune `detail_expanded`
                // entries for every torrent that's about to be removed.
                // Each removed hash maps to the prefix `"{info_hash}/"`
                // in the folder-key namespace; without this pruning the
                // set grows unboundedly across long-running sessions.
                for hash in &hashes {
                    st.prune_detail_expanded_for(hash);
                    st.prune_speed_history_for(hash);
                }
                (hashes, st.cmd_tx.clone())
            };
            if let Some(tx) = cmd_tx {
                let _ = tx.send(app::GuiCommand::RemoveTorrents {
                    hashes,
                    delete_files,
                });
            }
        });
    }

    // 6i. Wire keyboard shortcuts.
    {
        // Space: toggle pause/resume for selected torrents.
        let cb_state = state.clone();
        main_window.on_toggle_pause_resume(move || {
            let (selected, cmd_tx) = {
                let st = cb_state.lock();
                (st.selected.clone(), st.cmd_tx.clone())
            };
            if selected.is_empty() {
                return;
            }
            let Some(tx) = cmd_tx else { return };
            // We are on the main thread — can read the thread-local model directly.
            let all_paused = crate::poll::check_all_paused(&selected);
            let hashes: Vec<String> = selected.into_iter().collect();
            let cmd = if all_paused {
                app::GuiCommand::ResumeTorrents { hashes }
            } else {
                app::GuiCommand::PauseTorrents { hashes }
            };
            let _ = tx.send(cmd);
        });
    }
    {
        // Delete: open delete confirmation for selected torrents.
        let cb_state = state.clone();
        let weak = main_window.as_weak();
        main_window.on_delete_selected(move || {
            let count = {
                let st = cb_state.lock();
                i32::try_from(st.selected.len()).unwrap_or(i32::MAX)
            };
            if count == 0 {
                return;
            }
            let _ = weak.upgrade_in_event_loop(move |win| {
                win.set_delete_dialog_count(count);
                win.set_delete_dialog_delete_files(false);
                win.set_show_delete_dialog(true);
            });
        });
    }
    {
        // Ctrl+A: select all torrents.
        let cb_state = state.clone();
        main_window.on_select_all(move || {
            let (selected, primary) = {
                let mut st = cb_state.lock();
                let all_hashes = st.current_order.clone();
                st.select_all(&all_hashes);
                (st.selected.clone(), st.primary_selected().map(str::to_owned))
            };
            crate::poll::update_selection(&selected);
            crate::poll::update_primary_selection(primary.as_deref());
        });
    }
    {
        // Enter: stub toast for details panel.
        let weak = main_window.as_weak();
        main_window.on_show_details_stub(move || {
            bridge::show_toast(&weak, "Details panel: coming in M172", false);
        });
    }
    {
        // M173 Lane A task A7+A8: Ctrl+1..9 / Cmd+1..9 sidebar shortcut.
        // Slint forwards the raw digit text plus the focus-scope guard
        // already blocked any open dialog/menu. The Rust side validates
        // the platform accelerator via `accel::parse_sidebar_shortcut`
        // and resolves the slot to a Library predicate via
        // `sidebar_view::predicate_for_shortcut_slot` (slots 1..=8 →
        // LibraryFilter::ORDER; slot 9 currently no-ops).
        let weak = main_window.as_weak();
        let cb_state = state.clone();
        main_window.on_sidebar_shortcut(move |digit| {
            let Some(win) = weak.upgrade() else { return };
            let ctrl = win.get_ctrl_held();
            let meta = win.get_meta_held();
            let Some(slot) = accel::parse_sidebar_shortcut(digit.as_str(), ctrl, meta) else {
                return;
            };
            let Some(predicate) = sidebar_view::predicate_for_shortcut_slot(slot) else {
                return;
            };
            cb_state.lock().set_predicate(predicate);
        });
    }
    {
        // M173 Lane A task A8: sidebar row click → predicate change.
        // The Slint sidebar emits the SidebarSection::to_token() slug;
        // we parse it back into a SidebarPredicate and push onto
        // AppState. The next poll tick rebuilds the visible model.
        let cb_state = state.clone();
        main_window.on_sidebar_predicate_changed(move |token| {
            if let Some(section) = sidebar::SidebarSection::from_token(token.as_str()) {
                let predicate = sidebar::SidebarPredicate::from_section(&section);
                cb_state.lock().set_predicate(predicate);
            }
        });
    }
    {
        // M173 Lane A task A8: sidebar section collapse toggle.
        // Marks the sidebar config dirty so task A9 persists on quit.
        let cb_state = state.clone();
        main_window.on_sidebar_section_toggled(move |_kind, _collapsed| {
            cb_state.lock().sidebar_dirty = true;
        });
    }

    // ── M177 detail-pane callbacks ────────────────────────────────────
    {
        // Tab switch — propagate to AppState so the next poll tick gates
        // the per-tick file fetches (D-eng-2). M178: also clear any
        // pending file-priority popup state since switching tabs invalidates
        // the right-click target (D-eng-7).
        let cb_state = state.clone();
        let cb_weak = main_window.as_weak();
        main_window.on_detail_tab_changed(move |tab| {
            {
                let mut st = cb_state.lock();
                st.detail_active_tab = tab.to_string();
                st.pending_file_priority_target = None;
            }
            let _ = cb_weak.upgrade_in_event_loop(|win| {
                win.set_show_file_priority_popup(false);
            });
        });
    }
    {
        // Folder triangle click — toggle the key in AppState's
        // `detail_expanded` set. Default semantics: absent = expanded
        // (D-user-1), so the first toggle adds the key (collapse), the
        // next removes it (re-expand).
        let cb_state = state.clone();
        main_window.on_detail_folder_toggled(move |key| {
            cb_state.lock().toggle_detail_folder(key.as_str());
        });
    }
    {
        // Sequential-download toggle — fires a `SetSequentialDownload`
        // command via the bridge thread (no direct session call from
        // the main thread; the cmd_tx channel is the established
        // boundary).
        let cb_state = state.clone();
        let weak = main_window.as_weak();
        main_window.on_detail_sequential_toggled(move |enabled| {
            let st = cb_state.lock();
            let Some(hash) = st.primary_selected().map(str::to_owned) else {
                return;
            };
            let Some(tx) = st.cmd_tx.clone() else {
                return;
            };
            drop(st);
            // Optimistically flip the Slint property so the checkbox
            // reflects the click immediately; the next poll tick will
            // overwrite from `TorrentStats.sequential_download` in any
            // case, but the optimistic update prevents a flicker.
            let _ = weak.upgrade_in_event_loop(move |win| {
                win.set_detail_sequential(enabled);
            });
            let _ = tx.send(app::GuiCommand::SetSequentialDownload {
                info_hash: hash,
                enabled,
            });
        });
    }

    // ── M178 detail-pane callbacks (Lane D) ──────────────────────────
    {
        // File row left-click with modifiers: drives multi-select.
        let cb_state = state.clone();
        main_window.on_detail_file_clicked(move |index, ctrl, shift| {
            let Ok(idx) = usize::try_from(index) else {
                return;
            };
            let mut st = cb_state.lock();
            st.apply_file_click(idx, ctrl, shift);
            // A new selection invalidates any open popup target snapshot.
            st.pending_file_priority_target = None;
        });
    }
    {
        // File row right-click: snapshot the selection (or this row if
        // it isn't selected), set the pending target, and surface the
        // popup at the cursor position.
        let cb_state = state.clone();
        let cb_weak = main_window.as_weak();
        main_window.on_detail_file_right_clicked(move |index, x, y| {
            let Ok(idx) = usize::try_from(index) else {
                return;
            };
            let (info_hash, snapshot) = {
                let mut st = cb_state.lock();
                let Some(hash) = st.primary_selected().map(str::to_owned) else {
                    return;
                };
                // If the right-clicked row is NOT currently selected,
                // single-select it first (mirrors qBt + macOS Finder).
                if !st.detail_files_selected.contains(&idx) {
                    st.detail_files_selected.clear();
                    st.detail_files_selected.insert(idx);
                    st.last_clicked_file_index = Some(idx);
                }
                let snap: Vec<usize> = st.detail_files_selected.iter().copied().collect();
                st.pending_file_priority_target = Some((hash.clone(), snap.clone()));
                (hash, snap)
            };
            let _ = (info_hash, snapshot); // moved into the lock-scoped tuple
            let _ = cb_weak.upgrade_in_event_loop(move |win| {
                win.set_file_priority_popup_x(x);
                win.set_file_priority_popup_y(y);
                win.set_show_file_priority_popup(true);
            });
        });
    }
    {
        // Popup option click → dispatch SetFilePriority on the snapshot.
        let cb_state = state.clone();
        main_window.on_file_priority_selected(move |priority_int| {
            let (hash, indices, tx) = {
                let mut st = cb_state.lock();
                let Some((hash, indices)) = st.pending_file_priority_target.take() else {
                    return;
                };
                let Some(tx) = st.cmd_tx.clone() else {
                    return;
                };
                (hash, indices, tx)
            };
            let priority =
                irontide::core::FilePriority::from(u8::try_from(priority_int).unwrap_or(4));
            let _ = tx.send(app::GuiCommand::SetFilePriority {
                info_hash: hash,
                file_indices: indices,
                priority,
            });
        });
    }
    {
        // Popup dismiss (click-outside): clear the pending target.
        let cb_state = state.clone();
        main_window.on_file_priority_dismissed(move || {
            cb_state.lock().pending_file_priority_target = None;
        });
    }
    {
        // F9: Folder right-click → resolve folder path to contained file
        // indices, store as pending target, show priority popup.
        let cb_state = state.clone();
        let cb_weak = main_window.as_weak();
        main_window.on_detail_folder_right_clicked(move |key, x, y| {
            let key_str = key.to_string();
            // Key format: "{info_hash}/{folder_path}"
            let Some(slash_pos) = key_str.find('/') else {
                return;
            };
            let info_hash = key_str[..slash_pos].to_owned();
            let folder_path = std::path::Path::new(&key_str[slash_pos + 1..]);

            let mut st = cb_state.lock();
            let indices =
                crate::detail::collect_folder_file_indices(&st.detail_flat_files, folder_path);
            if indices.is_empty() {
                return;
            }
            st.pending_file_priority_target = Some((info_hash, indices));
            drop(st);

            let _ = cb_weak.upgrade_in_event_loop(move |win| {
                win.set_file_priority_popup_x(x);
                win.set_file_priority_popup_y(y);
                win.set_show_file_priority_popup(true);
            });
        });
    }
    {
        // Trackers tab "Reannounce" button click — torrent-wide
        // reannounce until the engine exposes a per-URL endpoint
        // (M180 polish).
        let cb_state = state.clone();
        main_window.on_detail_reannounce(move |url| {
            let st = cb_state.lock();
            let Some(hash) = st.primary_selected().map(str::to_owned) else {
                return;
            };
            let Some(tx) = st.cmd_tx.clone() else {
                return;
            };
            drop(st);
            let _ = tx.send(app::GuiCommand::ReannounceTracker {
                info_hash: hash,
                url: url.to_string(),
            });
        });
    }

    // ── M180 speed-tab callbacks ───────────────────────────────────
    {
        let cb_state = state.clone();
        main_window.on_detail_speed_dl_limit_applied(move |input| {
            let st = cb_state.lock();
            let Some(hash) = st.primary_selected().map(str::to_owned) else {
                return;
            };
            let Some(tx) = st.cmd_tx.clone() else {
                return;
            };
            drop(st);
            match speed::parse_rate_limit(input.as_str()) {
                Some(bytes) => {
                    let _ = tx.send(app::GuiCommand::SetTorrentRateLimit {
                        info_hash: hash,
                        download_limit: Some(bytes),
                        upload_limit: None,
                    });
                }
                None => {
                    tracing::warn!(input = %input, "invalid DL rate limit input");
                }
            }
        });
    }
    {
        let cb_state = state.clone();
        main_window.on_detail_speed_ul_limit_applied(move |input| {
            let st = cb_state.lock();
            let Some(hash) = st.primary_selected().map(str::to_owned) else {
                return;
            };
            let Some(tx) = st.cmd_tx.clone() else {
                return;
            };
            drop(st);
            match speed::parse_rate_limit(input.as_str()) {
                Some(bytes) => {
                    let _ = tx.send(app::GuiCommand::SetTorrentRateLimit {
                        info_hash: hash,
                        download_limit: None,
                        upload_limit: Some(bytes),
                    });
                }
                None => {
                    tracing::warn!(input = %input, "invalid UL rate limit input");
                }
            }
        });
    }

    // 6j. Wire Tweaks overlay callbacks (M172b Lane B + M176 D12).
    // The four token-affecting axes use the `wire_skin_axis!` macro so
    // every new axis is one line, not twelve.
    wire_skin_axis!(
        main_window,
        state,
        on_tweaks_skin_changed,
        skin,
        skin::Skin,
        set_current_skin
    );
    wire_skin_axis!(
        main_window,
        state,
        on_tweaks_theme_changed,
        theme,
        skin::Theme,
        set_current_theme
    );
    wire_skin_axis!(
        main_window,
        state,
        on_tweaks_density_changed,
        density,
        skin::Density,
        set_current_density
    );
    wire_skin_axis!(
        main_window,
        state,
        on_tweaks_radius_changed,
        radius,
        skin::RadiusPreset,
        set_current_radius
    );

    // M176: Layout. Doesn't fit `wire_skin_axis!` because (1) the
    // user-facing label ("3-pane" / "Drawer" / "Command") is mapped to
    // an L1/L2/L3 token via `Layout::from_label`, not `FromStr`, and
    // (2) Layout doesn't affect Tokens, so `apply()` is a no-op for
    // this axis. We also refresh `inspector-shown` because its effective
    // value depends on the active layout when the user hasn't set an
    // override.
    {
        let weak = main_window.as_weak();
        let cb_state = state.clone();
        main_window.on_tweaks_layout_changed(move |label| {
            let Some(new_layout) = skin::Layout::from_label(label.as_str()) else {
                tracing::warn!(invalid = label.as_str(), "unknown layout label, ignored");
                return;
            };
            let inspector_shown = {
                let mut st = cb_state.lock();
                st.skin.layout = new_layout;
                st.skin_dirty = true;
                st.skin
                    .inspector_shown
                    .unwrap_or_else(|| skin::default_inspector_shown(new_layout))
            };
            if let Some(win) = weak.upgrade() {
                win.set_current_layout_label(label.clone());
                win.set_inspector_shown(inspector_shown);
            }
        });
    }

    // F7: Ctrl+Shift+L — cycle layout L1→L2→L3→L1. Reuses the existing
    // tweaks_layout_changed handler to avoid duplicating layout-change logic.
    {
        let weak = main_window.as_weak();
        let cb_state = state.clone();
        main_window.on_layout_cycle(move || {
            let label = {
                let st = cb_state.lock();
                st.skin.layout.cycle().label().to_owned()
            };
            if let Some(win) = weak.upgrade() {
                win.invoke_tweaks_layout_changed(label.into());
            }
        });
    }

    // M176: Inspector toggle (⌘I). Captures the user's explicit
    // preference so layout switches don't clobber it. No-op in L1
    // because the inline detail-pane is always visible there.
    {
        let weak = main_window.as_weak();
        let cb_state = state.clone();
        main_window.on_inspector_toggle(move || {
            let new_value = {
                let mut st = cb_state.lock();
                if st.skin.layout == skin::Layout::L1 {
                    return;
                }
                let current = st
                    .skin
                    .inspector_shown
                    .unwrap_or_else(|| skin::default_inspector_shown(st.skin.layout));
                let v = !current;
                st.skin.inspector_shown = Some(v);
                st.skin_dirty = true;
                v
            };
            if let Some(win) = weak.upgrade() {
                win.set_inspector_shown(new_value);
            }
        });
    }

    // M176: L3 sidebar toggle (Ctrl+Shift+S / Cmd+Shift+S). Cycles
    // between icons-only and hidden. No-op outside L3.
    {
        let weak = main_window.as_weak();
        let cb_state = state.clone();
        main_window.on_l3_sidebar_toggle(move || {
            let new_mode = {
                let mut st = cb_state.lock();
                if st.skin.layout != skin::Layout::L3 {
                    return;
                }
                let next = match st.skin.l3_sidebar_mode {
                    skin::L3SidebarMode::Icons => skin::L3SidebarMode::Hidden,
                    skin::L3SidebarMode::Hidden => skin::L3SidebarMode::Icons,
                };
                st.skin.l3_sidebar_mode = next;
                st.skin_dirty = true;
                next
            };
            if let Some(win) = weak.upgrade() {
                win.set_current_l3_sidebar_mode(new_mode.to_string().into());
            }
        });
    }

    // 7. Spawn session thread.
    let session_handle =
        bridge::spawn_session_thread(settings, main_window.as_weak(), shutdown_rx, state.clone());

    // 8. Run Slint event loop (blocks until window is closed).
    main_window.run()?;

    // 9. Save GUI config if any dirty field (columns / skin / sidebar).
    {
        // Refresh collapsed state from the live window so toggles made
        // while the app was running are captured even if AppState was
        // not updated synchronously by the callback.
        if let Some(win) = main_window.as_weak().upgrade() {
            let mut st = state.lock();
            st.sidebar_library_collapsed = win.get_sidebar_library_collapsed();
            st.sidebar_category_collapsed = win.get_sidebar_category_collapsed();
            st.sidebar_tag_collapsed = win.get_sidebar_tag_collapsed();
            st.sidebar_tracker_collapsed = win.get_sidebar_tracker_collapsed();
        }
        let st = state.lock();
        if st.columns_dirty || st.skin_dirty || st.sidebar_dirty {
            let mut gui = st.columns.to_gui_config();
            st.skin.populate_gui_config(&mut gui);
            // M173 Lane A task A9: persist [gui.sidebar].
            gui.sidebar = Some(st.to_sidebar_config());
            if let Err(e) = irontide_config::save_gui_config(None, &gui) {
                tracing::warn!("failed to save GUI config: {e}");
            }
        }
    }

    // 10. Signal shutdown to background thread.
    if let Some(tx) = state.lock().shutdown_tx.take() {
        let _ = tx.send(());
    }

    // 11. Wait for background thread to finish.
    if let Err(e) = session_handle.join() {
        eprintln!("session thread panicked: {e:?}");
    }

    Ok(())
}
