mod app;
mod bridge;
mod columns;
mod error;
mod format;
mod panic_hook;
mod poll;

// Generated by slint_build::compile in build.rs
slint::include_modules!();

use std::sync::Arc;

use parking_lot::Mutex;
use slint::Model as _;

fn main() -> Result<(), error::GuiError> {
    // 1. Install panic hook.
    panic_hook::install();

    // 2. Init tracing.
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env().unwrap_or_else(|_| "info".into()),
        )
        .with_target(false)
        .init();

    // 3. Load settings + column config.
    let config = irontide_config::load(None, &irontide_config::ConfigFile::default())
        .map_err(|e| error::GuiError::Config(e.to_string()))?;
    let gui_config = {
        let path = irontide_config::resolve_config_path(None);
        if path.exists() {
            let text = std::fs::read_to_string(&path).unwrap_or_default();
            let cf: irontide_config::ConfigFile = toml::from_str(&text).unwrap_or_default();
            cf.gui
        } else {
            irontide_config::GuiConfig::default()
        }
    };
    let col_config = columns::ColumnConfig::from_gui_config(&gui_config);
    let settings = config;

    // 4. Create shutdown channel + app state.
    let (shutdown_tx, shutdown_rx) = tokio::sync::oneshot::channel();
    let state = Arc::new(Mutex::new(app::AppState::new(shutdown_tx, col_config)));

    // 5. Create main window.
    let main_window = MainWindow::new()?;

    // 6. Wire menu callbacks.
    let weak = main_window.as_weak();
    let cb_state = state.clone();
    main_window.on_menu_file_action(move |index| {
        if let Some(action) = app::MenuAction::from_index(index) {
            bridge::handle_menu_action(action, &weak, &cb_state);
        }
    });

    // 6b. Wire sort callback.
    {
        let cb_state = state.clone();
        main_window.on_sort_requested(move |col_index| {
            let Some(col) = columns::ColumnId::from_index(col_index) else {
                return;
            };
            let mut st = cb_state.lock();
            if st.sort.column == col {
                st.sort.ascending = !st.sort.ascending;
            } else {
                st.sort.column = col;
                st.sort.ascending = true;
            }
        });
    }

    // 6c. Wire row-click callback.
    {
        let cb_state = state.clone();
        main_window.on_row_clicked(move |info_hash, shift, ctrl| {
            let hash = info_hash.as_str();
            let selected = {
                let mut st = cb_state.lock();
                if ctrl {
                    st.selection_ctrl_click(hash);
                } else if shift {
                    st.selection_shift_click(hash);
                } else {
                    st.selection_click(hash);
                }
                st.selected.clone()
            };
            crate::poll::update_selection(&selected);
        });
    }

    // 6d. Wire add-magnet dialog callbacks.
    {
        let cb_state = state.clone();
        main_window.on_add_magnet_confirmed(move |uri, dir| {
            let cmd_tx = {
                let st = cb_state.lock();
                st.cmd_tx.clone()
            };
            if let Some(tx) = cmd_tx {
                let download_dir = if dir.is_empty() {
                    None
                } else {
                    Some(dir.to_string())
                };
                let _ = tx.send(app::GuiCommand::AddMagnet {
                    uri: uri.to_string(),
                    download_dir,
                });
            }
        });
    }

    {
        let weak = main_window.as_weak();
        main_window.on_browse_magnet_download_dir(move || {
            bridge::handle_browse_download_dir(&weak);
        });
    }

    // 6e. Wire add-torrent dialog callbacks.
    {
        let cb_state = state.clone();
        main_window.on_add_torrent_confirmed(move |path, dir| {
            let cmd_tx = {
                let st = cb_state.lock();
                st.cmd_tx.clone()
            };
            if let Some(tx) = cmd_tx {
                let download_dir = if dir.is_empty() {
                    None
                } else {
                    Some(dir.to_string())
                };
                let _ = tx.send(app::GuiCommand::AddTorrentFile {
                    path: path.to_string(),
                    download_dir,
                });
            }
        });
    }

    {
        let weak = main_window.as_weak();
        main_window.on_browse_torrent_file(move || {
            bridge::handle_browse_torrent_file(&weak);
        });
    }

    {
        let weak = main_window.as_weak();
        main_window.on_browse_torrent_download_dir(move || {
            bridge::handle_browse_download_dir(&weak);
        });
    }

    // 6f. Wire right-click context menu.
    {
        let cb_state = state.clone();
        let weak = main_window.as_weak();
        main_window.on_row_right_clicked(move |info_hash, x, y| {
            let hash = info_hash.to_string();
            // If right-clicked row is not selected, select it first.
            let selected = {
                let mut st = cb_state.lock();
                if !st.selected.contains(&hash) {
                    st.selection_click(&hash);
                }
                st.selected.clone()
            };
            // Immediately update selection in model.
            crate::poll::update_selection(&selected);

            // Show context menu at cursor position.
            let _ = weak.upgrade_in_event_loop(move |win| {
                // Compute smart enable/disable state from the torrent model.
                let model = win.get_torrent_model();
                let mut state_strings: Vec<String> = Vec::new();

                for i in 0..model.row_count() {
                    if let Some(row) = model.row_data(i)
                        && selected.contains(row.info_hash.as_str())
                    {
                        state_strings.push(row.state.to_string());
                    }
                }

                let state_refs: Vec<&str> = state_strings.iter().map(String::as_str).collect();
                let ctx = app::ContextMenuState::compute(&state_refs);

                win.set_ctx_can_pause(ctx.can_pause);
                win.set_ctx_can_resume(ctx.can_resume);
                win.set_ctx_can_seed_only(ctx.can_seed_only);
                win.set_ctx_can_resume_download(ctx.can_resume_download);
                win.set_ctx_can_recheck(ctx.can_recheck);

                win.set_context_menu_x(x);
                win.set_context_menu_y(y);
                win.set_show_context_menu(true);
            });
        });
    }

    // 6g. Wire context menu action dispatch.
    {
        let cb_state = state.clone();
        let weak = main_window.as_weak();
        main_window.on_context_action(move |action_index| {
            let Some(action) = app::ContextAction::from_index(action_index) else {
                return;
            };
            let hashes: Vec<String> = {
                let st = cb_state.lock();
                st.selected.iter().cloned().collect()
            };

            // Remove/RemoveAndDelete: show confirmation dialog instead of immediate action.
            if matches!(
                action,
                app::ContextAction::Remove | app::ContextAction::RemoveAndDelete
            ) {
                let delete_files = matches!(action, app::ContextAction::RemoveAndDelete);
                let count = i32::try_from(hashes.len()).unwrap_or(i32::MAX);
                let _ = weak.upgrade_in_event_loop(move |win| {
                    win.set_delete_dialog_count(count);
                    win.set_delete_dialog_delete_files(delete_files);
                    win.set_show_delete_dialog(true);
                });
                return;
            }

            let cmd_tx = {
                let st = cb_state.lock();
                st.cmd_tx.clone()
            };
            let Some(tx) = cmd_tx else { return };

            use app::ContextAction;
            let cmd = match action {
                ContextAction::Pause => app::GuiCommand::PauseTorrents { hashes },
                ContextAction::Resume => app::GuiCommand::ResumeTorrents { hashes },
                ContextAction::SeedOnly => app::GuiCommand::SetSeedMode {
                    hashes,
                    enabled: true,
                },
                ContextAction::ResumeDownload => app::GuiCommand::SetSeedMode {
                    hashes,
                    enabled: false,
                },
                ContextAction::Recheck => app::GuiCommand::ForceRecheck { hashes },
                ContextAction::ForceReannounce => app::GuiCommand::ForceReannounce { hashes },
                // Handled by the confirmation dialog above; unreachable here.
                ContextAction::Remove | ContextAction::RemoveAndDelete => return,
            };
            let _ = tx.send(cmd);
        });
    }

    // 6h. Wire delete confirmation callback.
    {
        let cb_state = state.clone();
        main_window.on_delete_confirmed(move |delete_files| {
            let (hashes, cmd_tx) = {
                let st = cb_state.lock();
                (
                    st.selected.iter().cloned().collect::<Vec<_>>(),
                    st.cmd_tx.clone(),
                )
            };
            if let Some(tx) = cmd_tx {
                let _ = tx.send(app::GuiCommand::RemoveTorrents {
                    hashes,
                    delete_files,
                });
            }
        });
    }

    // 7. Spawn session thread.
    let session_handle =
        bridge::spawn_session_thread(settings, main_window.as_weak(), shutdown_rx, state.clone());

    // 8. Run Slint event loop (blocks until window is closed).
    main_window.run()?;

    // 9. Save column config if dirty.
    {
        let st = state.lock();
        if st.columns_dirty {
            let gui = st.columns.to_gui_config();
            if let Err(e) = irontide_config::save_gui_config(None, &gui) {
                tracing::warn!("failed to save GUI config: {e}");
            }
        }
    }

    // 10. Signal shutdown to background thread.
    if let Some(tx) = state.lock().shutdown_tx.take() {
        let _ = tx.send(());
    }

    // 11. Wait for background thread to finish.
    if let Err(e) = session_handle.join() {
        eprintln!("session thread panicked: {e:?}");
    }

    Ok(())
}
