mod accel;
mod app;
mod bridge;
mod columns;
mod error;
mod format;
mod panic_hook;
mod poll;
mod sidebar;
mod sidebar_view;
mod skin;
mod skin_tokens;

// Generated by slint_build::compile in build.rs
slint::include_modules!();

use std::sync::Arc;

use parking_lot::Mutex;
use slint::Model as _;

fn main() -> Result<(), error::GuiError> {
    // 1. Install panic hook.
    panic_hook::install();

    // 2. Init tracing.
    tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env().unwrap_or_else(|_| "info".into()),
        )
        .with_target(false)
        .init();

    // 3. Load settings + column config.
    let config = irontide_config::load(None, &irontide_config::ConfigFile::default())
        .map_err(|e| error::GuiError::Config(e.to_string()))?;
    let gui_config = {
        let path = irontide_config::resolve_config_path(None);
        if path.exists() {
            let text = std::fs::read_to_string(&path).unwrap_or_default();
            let cf: irontide_config::ConfigFile = toml::from_str(&text).unwrap_or_default();
            cf.gui
        } else {
            irontide_config::GuiConfig::default()
        }
    };
    let col_config = columns::ColumnConfig::from_gui_config(&gui_config);
    let skin_settings = skin::SkinSettings::from_gui_config(&gui_config);
    let settings = config;

    // 4. Create shutdown channel + app state.
    let (shutdown_tx, shutdown_rx) = tokio::sync::oneshot::channel();
    let mut initial_state = app::AppState::new(shutdown_tx, col_config, skin_settings);
    // M173 Lane A task A9: hydrate persisted sidebar state. Absent
    // [gui.sidebar] table → all defaults; corrupt token → silent
    // fallback to Library::All.
    if let Some(sb) = gui_config.sidebar.as_ref() {
        initial_state.load_sidebar_config(sb);
    }
    let state = Arc::new(Mutex::new(initial_state));

    // 5. Create main window + push initial skin into Tokens global.
    let main_window = MainWindow::new()?;
    {
        let weak = main_window.as_weak();
        let st = state.lock();
        st.skin.apply(&weak);
        // Seed the Tweaks overlay's current-* pill state so the UI
        // reflects the persisted config on first paint.
        main_window.set_current_skin(st.skin.skin.to_string().into());
        main_window.set_current_theme(st.skin.theme.to_string().into());
        main_window.set_current_density(st.skin.density.to_string().into());
        main_window.set_current_radius(st.skin.radius.to_string().into());
        // M173 Lane A task A9: seed sidebar collapsed flags from
        // persisted state so the first-paint sidebar matches the
        // user's last session.
        main_window.set_sidebar_library_collapsed(st.sidebar_library_collapsed);
        main_window.set_sidebar_category_collapsed(st.sidebar_category_collapsed);
        main_window.set_sidebar_tag_collapsed(st.sidebar_tag_collapsed);
        main_window.set_sidebar_tracker_collapsed(st.sidebar_tracker_collapsed);
    }

    // 6. Wire menu callbacks.
    let weak = main_window.as_weak();
    let cb_state = state.clone();
    main_window.on_menu_file_action(move |index| {
        if let Some(action) = app::MenuAction::from_index(index) {
            bridge::handle_menu_action(action, &weak, &cb_state);
        }
    });

    // 6b. Wire sort callback.
    {
        let cb_state = state.clone();
        main_window.on_sort_requested(move |col_index| {
            let Some(col) = columns::ColumnId::from_index(col_index) else {
                return;
            };
            let mut st = cb_state.lock();
            if st.sort.column == col {
                st.sort.ascending = !st.sort.ascending;
            } else {
                st.sort.column = col;
                st.sort.ascending = true;
            }
        });
    }

    // 6c. Wire row-click callback.
    {
        let cb_state = state.clone();
        main_window.on_row_clicked(move |info_hash, shift, ctrl| {
            let hash = info_hash.as_str();
            let selected = {
                let mut st = cb_state.lock();
                if ctrl {
                    st.selection_ctrl_click(hash);
                } else if shift {
                    st.selection_shift_click(hash);
                } else {
                    st.selection_click(hash);
                }
                st.selected.clone()
            };
            crate::poll::update_selection(&selected);
        });
    }

    // 6d. Wire add-magnet dialog callbacks.
    {
        let cb_state = state.clone();
        main_window.on_add_magnet_confirmed(move |uri, dir| {
            let cmd_tx = {
                let st = cb_state.lock();
                st.cmd_tx.clone()
            };
            if let Some(tx) = cmd_tx {
                let download_dir = if dir.is_empty() {
                    None
                } else {
                    Some(dir.to_string())
                };
                let _ = tx.send(app::GuiCommand::AddMagnet {
                    uri: uri.to_string(),
                    download_dir,
                });
            }
        });
    }

    {
        let weak = main_window.as_weak();
        let cb_state = state.clone();
        main_window.on_browse_magnet_download_dir(move || {
            bridge::handle_browse_download_dir(&weak, &cb_state);
        });
    }

    // 6e. Wire add-torrent dialog callbacks.
    {
        let cb_state = state.clone();
        main_window.on_add_torrent_confirmed(move |path, dir| {
            let cmd_tx = {
                let st = cb_state.lock();
                st.cmd_tx.clone()
            };
            if let Some(tx) = cmd_tx {
                let download_dir = if dir.is_empty() {
                    None
                } else {
                    Some(dir.to_string())
                };
                let _ = tx.send(app::GuiCommand::AddTorrentFile {
                    path: path.to_string(),
                    download_dir,
                });
            }
        });
    }

    {
        let weak = main_window.as_weak();
        main_window.on_browse_torrent_file(move || {
            bridge::handle_browse_torrent_file(&weak);
        });
    }

    {
        let weak = main_window.as_weak();
        let cb_state = state.clone();
        main_window.on_browse_torrent_download_dir(move || {
            bridge::handle_browse_download_dir(&weak, &cb_state);
        });
    }

    // 6f. Wire right-click context menu.
    {
        let cb_state = state.clone();
        let weak = main_window.as_weak();
        main_window.on_row_right_clicked(move |info_hash, x, y| {
            let hash = info_hash.to_string();
            // If right-clicked row is not selected, select it first.
            let selected = {
                let mut st = cb_state.lock();
                if !st.selected.contains(&hash) {
                    st.selection_click(&hash);
                }
                st.selected.clone()
            };
            // Immediately update selection in model.
            crate::poll::update_selection(&selected);

            // Show context menu at cursor position.
            let _ = weak.upgrade_in_event_loop(move |win| {
                // Compute smart enable/disable state from the torrent model.
                let model = win.get_torrent_model();
                let mut state_strings: Vec<String> = Vec::new();

                for i in 0..model.row_count() {
                    if let Some(row) = model.row_data(i)
                        && selected.contains(row.info_hash.as_str())
                    {
                        state_strings.push(row.state.to_string());
                    }
                }

                let state_refs: Vec<&str> = state_strings.iter().map(String::as_str).collect();
                let ctx = app::ContextMenuState::compute(&state_refs);

                win.set_ctx_can_pause(ctx.can_pause);
                win.set_ctx_can_resume(ctx.can_resume);
                win.set_ctx_can_seed_only(ctx.can_seed_only);
                win.set_ctx_can_resume_download(ctx.can_resume_download);
                win.set_ctx_can_recheck(ctx.can_recheck);

                win.set_context_menu_x(x);
                win.set_context_menu_y(y);
                win.set_show_context_menu(true);
            });
        });
    }

    // 6g. Wire context menu action dispatch.
    {
        let cb_state = state.clone();
        let weak = main_window.as_weak();
        main_window.on_context_action(move |action_index| {
            let Some(action) = app::ContextAction::from_index(action_index) else {
                return;
            };
            let hashes: Vec<String> = {
                let st = cb_state.lock();
                st.selected.iter().cloned().collect()
            };

            // Remove/RemoveAndDelete: show confirmation dialog instead of immediate action.
            if matches!(
                action,
                app::ContextAction::Remove | app::ContextAction::RemoveAndDelete
            ) {
                let delete_files = matches!(action, app::ContextAction::RemoveAndDelete);
                let count = i32::try_from(hashes.len()).unwrap_or(i32::MAX);
                let _ = weak.upgrade_in_event_loop(move |win| {
                    win.set_delete_dialog_count(count);
                    win.set_delete_dialog_delete_files(delete_files);
                    win.set_show_delete_dialog(true);
                });
                return;
            }

            let cmd_tx = {
                let st = cb_state.lock();
                st.cmd_tx.clone()
            };
            let Some(tx) = cmd_tx else { return };

            use app::ContextAction;
            let cmd = match action {
                ContextAction::Pause => app::GuiCommand::PauseTorrents { hashes },
                ContextAction::Resume => app::GuiCommand::ResumeTorrents { hashes },
                ContextAction::SeedOnly => app::GuiCommand::SetSeedMode {
                    hashes,
                    enabled: true,
                },
                ContextAction::ResumeDownload => app::GuiCommand::SetSeedMode {
                    hashes,
                    enabled: false,
                },
                ContextAction::Recheck => app::GuiCommand::ForceRecheck { hashes },
                ContextAction::ForceReannounce => app::GuiCommand::ForceReannounce { hashes },
                // Handled by the confirmation dialog above; unreachable here.
                ContextAction::Remove | ContextAction::RemoveAndDelete => return,
            };
            let _ = tx.send(cmd);
        });
    }

    // 6h. Wire delete confirmation callback.
    {
        let cb_state = state.clone();
        main_window.on_delete_confirmed(move |delete_files| {
            let (hashes, cmd_tx) = {
                let st = cb_state.lock();
                (
                    st.selected.iter().cloned().collect::<Vec<_>>(),
                    st.cmd_tx.clone(),
                )
            };
            if let Some(tx) = cmd_tx {
                let _ = tx.send(app::GuiCommand::RemoveTorrents {
                    hashes,
                    delete_files,
                });
            }
        });
    }

    // 6i. Wire keyboard shortcuts.
    {
        // Space: toggle pause/resume for selected torrents.
        let cb_state = state.clone();
        main_window.on_toggle_pause_resume(move || {
            let (selected, cmd_tx) = {
                let st = cb_state.lock();
                (st.selected.clone(), st.cmd_tx.clone())
            };
            if selected.is_empty() {
                return;
            }
            let Some(tx) = cmd_tx else { return };
            // We are on the main thread — can read the thread-local model directly.
            let all_paused = crate::poll::check_all_paused(&selected);
            let hashes: Vec<String> = selected.into_iter().collect();
            let cmd = if all_paused {
                app::GuiCommand::ResumeTorrents { hashes }
            } else {
                app::GuiCommand::PauseTorrents { hashes }
            };
            let _ = tx.send(cmd);
        });
    }
    {
        // Delete: open delete confirmation for selected torrents.
        let cb_state = state.clone();
        let weak = main_window.as_weak();
        main_window.on_delete_selected(move || {
            let count = {
                let st = cb_state.lock();
                i32::try_from(st.selected.len()).unwrap_or(i32::MAX)
            };
            if count == 0 {
                return;
            }
            let _ = weak.upgrade_in_event_loop(move |win| {
                win.set_delete_dialog_count(count);
                win.set_delete_dialog_delete_files(false);
                win.set_show_delete_dialog(true);
            });
        });
    }
    {
        // Ctrl+A: select all torrents.
        let cb_state = state.clone();
        main_window.on_select_all(move || {
            let selected = {
                let mut st = cb_state.lock();
                let all_hashes = st.current_order.clone();
                st.select_all(&all_hashes);
                st.selected.clone()
            };
            crate::poll::update_selection(&selected);
        });
    }
    {
        // Enter: stub toast for details panel.
        let weak = main_window.as_weak();
        main_window.on_show_details_stub(move || {
            bridge::show_toast(&weak, "Details panel: coming in M172", false);
        });
    }
    {
        // M173 Lane A task A7+A8: Ctrl+1..9 / Cmd+1..9 sidebar shortcut.
        // Slint forwards the raw digit text plus the focus-scope guard
        // already blocked any open dialog/menu. The Rust side validates
        // the platform accelerator via `accel::parse_sidebar_shortcut`
        // and resolves the slot to a Library predicate via
        // `sidebar_view::predicate_for_shortcut_slot` (slots 1..=8 →
        // LibraryFilter::ORDER; slot 9 currently no-ops).
        let weak = main_window.as_weak();
        let cb_state = state.clone();
        main_window.on_sidebar_shortcut(move |digit| {
            let Some(win) = weak.upgrade() else { return };
            let ctrl = win.get_ctrl_held();
            let meta = win.get_meta_held();
            let Some(slot) = accel::parse_sidebar_shortcut(digit.as_str(), ctrl, meta) else {
                return;
            };
            let Some(predicate) = sidebar_view::predicate_for_shortcut_slot(slot) else {
                return;
            };
            cb_state.lock().set_predicate(predicate);
        });
    }
    {
        // M173 Lane A task A8: sidebar row click → predicate change.
        // The Slint sidebar emits the SidebarSection::to_token() slug;
        // we parse it back into a SidebarPredicate and push onto
        // AppState. The next poll tick rebuilds the visible model.
        let cb_state = state.clone();
        main_window.on_sidebar_predicate_changed(move |token| {
            if let Some(section) = sidebar::SidebarSection::from_token(token.as_str()) {
                let predicate = sidebar::SidebarPredicate::from_section(&section);
                cb_state.lock().set_predicate(predicate);
            }
        });
    }
    {
        // M173 Lane A task A8: sidebar section collapse toggle.
        // Marks the sidebar config dirty so task A9 persists on quit.
        let cb_state = state.clone();
        main_window.on_sidebar_section_toggled(move |_kind, _collapsed| {
            cb_state.lock().sidebar_dirty = true;
        });
    }

    // 6j. Wire Tweaks overlay callbacks (M172b Lane B).
    {
        use std::str::FromStr as _;
        let weak = main_window.as_weak();
        let cb_state = state.clone();
        main_window.on_tweaks_skin_changed(move |s| {
            if let Ok(new_skin) = skin::Skin::from_str(s.as_str()) {
                let skin_settings = {
                    let mut st = cb_state.lock();
                    st.skin.skin = new_skin;
                    st.skin_dirty = true;
                    st.skin
                };
                skin_settings.apply(&weak);
                if let Some(win) = weak.upgrade() {
                    win.set_current_skin(s.clone());
                }
            }
        });
    }
    {
        use std::str::FromStr as _;
        let weak = main_window.as_weak();
        let cb_state = state.clone();
        main_window.on_tweaks_theme_changed(move |s| {
            if let Ok(new_theme) = skin::Theme::from_str(s.as_str()) {
                let skin_settings = {
                    let mut st = cb_state.lock();
                    st.skin.theme = new_theme;
                    st.skin_dirty = true;
                    st.skin
                };
                skin_settings.apply(&weak);
                if let Some(win) = weak.upgrade() {
                    win.set_current_theme(s.clone());
                }
            }
        });
    }
    {
        use std::str::FromStr as _;
        let weak = main_window.as_weak();
        let cb_state = state.clone();
        main_window.on_tweaks_density_changed(move |s| {
            if let Ok(new_density) = skin::Density::from_str(s.as_str()) {
                let skin_settings = {
                    let mut st = cb_state.lock();
                    st.skin.density = new_density;
                    st.skin_dirty = true;
                    st.skin
                };
                skin_settings.apply(&weak);
                if let Some(win) = weak.upgrade() {
                    win.set_current_density(s.clone());
                }
            }
        });
    }
    {
        use std::str::FromStr as _;
        let weak = main_window.as_weak();
        let cb_state = state.clone();
        main_window.on_tweaks_radius_changed(move |s| {
            if let Ok(new_radius) = skin::RadiusPreset::from_str(s.as_str()) {
                let skin_settings = {
                    let mut st = cb_state.lock();
                    st.skin.radius = new_radius;
                    st.skin_dirty = true;
                    st.skin
                };
                skin_settings.apply(&weak);
                if let Some(win) = weak.upgrade() {
                    win.set_current_radius(s.clone());
                }
            }
        });
    }

    // 7. Spawn session thread.
    let session_handle =
        bridge::spawn_session_thread(settings, main_window.as_weak(), shutdown_rx, state.clone());

    // 8. Run Slint event loop (blocks until window is closed).
    main_window.run()?;

    // 9. Save GUI config if any dirty field (columns / skin / sidebar).
    {
        // Refresh collapsed state from the live window so toggles made
        // while the app was running are captured even if AppState was
        // not updated synchronously by the callback.
        if let Some(win) = main_window.as_weak().upgrade() {
            let mut st = state.lock();
            st.sidebar_library_collapsed = win.get_sidebar_library_collapsed();
            st.sidebar_category_collapsed = win.get_sidebar_category_collapsed();
            st.sidebar_tag_collapsed = win.get_sidebar_tag_collapsed();
            st.sidebar_tracker_collapsed = win.get_sidebar_tracker_collapsed();
        }
        let st = state.lock();
        if st.columns_dirty || st.skin_dirty || st.sidebar_dirty {
            let mut gui = st.columns.to_gui_config();
            st.skin.populate_gui_config(&mut gui);
            // M173 Lane A task A9: persist [gui.sidebar].
            gui.sidebar = Some(st.to_sidebar_config());
            if let Err(e) = irontide_config::save_gui_config(None, &gui) {
                tracing::warn!("failed to save GUI config: {e}");
            }
        }
    }

    // 10. Signal shutdown to background thread.
    if let Some(tx) = state.lock().shutdown_tx.take() {
        let _ = tx.send(());
    }

    // 11. Wait for background thread to finish.
    if let Err(e) = session_handle.join() {
        eprintln!("session thread panicked: {e:?}");
    }

    Ok(())
}
